services:
  - type: web
    runtime: node
    name: findroom-app
    plan: starter
    buildCommand: npm --prefix server install --omit=dev && npm --prefix client install --include=dev && npm --prefix client run build
    startCommand: npm start
    disk:
      name: findroom-data
      mountPath: /opt/render/project/src/server/.mongo-data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
